// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult, type UnlistenFn } from 'taurpc'
export type AccountProfile = {
	id: string,
	accountType: string,
	username: string,
	uuid: string,
	skinUrl: string | null,
	isActive: boolean,
	createdAt: number,
};

export type ElySkinItem = {
	id: number,
	skinUrl: string,
	isSlim: boolean,
	countWearers: number,
	countCubes: number,
	countViews: number,
	tags: string[],
};

export type ElySkinsCatalogResponse = {
	items: ElySkinItem[],
	totalItems: number,
	currentPage: number,
	lastPage: number,
};

export type MemorySettings = {
	minRamMb: number,
	maxRamMb: number,
};

export type Result<T, E> = {
	ok: T,
	err: E,
};

export type SystemMemoryInfo = {
	totalBytes: number,
	availableBytes: number,
	usedBytes: number,
	totalMb: number,
	availableMb: number,
	usedMb: number,
};
const ARGS_MAP = {"":{"add_offline_account":["username"],"apply_ely_skin":["account_id","skin_id","password"],"ely_login":["username","password"],"get_accounts":[],"get_active_account_token":[],"get_ely_skins":["page","query","sort","model"],"get_memory_settings":[],"get_skin_data_url":["skin_url"],"get_system_memory":[],"greet":["name"],"has_ely_web_credentials":["account_id"],"on_memory_changed":["settings"],"remove_account":["account_id"],"reorder_accounts":["account_ids"],"save_skin_to_downloads":["username","skin_url"],"set_active_account":["account_id"],"set_memory_settings":["min_ram_mb","max_ram_mb"],"upload_ely_skin":["account_id","image_base64","password"]}};

const RESULT_MAP = {"":{"add_offline_account":true,"apply_ely_skin":true,"ely_login":true,"get_accounts":true,"get_active_account_token":true,"get_ely_skins":true,"get_memory_settings":true,"get_skin_data_url":true,"get_system_memory":true,"greet":false,"has_ely_web_credentials":true,"on_memory_changed":false,"remove_account":true,"reorder_accounts":true,"save_skin_to_downloads":true,"set_active_account":true,"set_memory_settings":true,"upload_ely_skin":true}};

export type Router = {
	"": {
		add_offline_account: (username: string) => Promise<AccountProfile>,
		apply_ely_skin: (accountId: string, skinId: number, password: string | null) => Promise<null>,
		ely_login: (username: string, password: string) => Promise<AccountProfile>,
		get_accounts: () => Promise<AccountProfile[]>,
		get_active_account_token: () => Promise<string>,
		get_ely_skins: (page: number, query: string | null, sort: string | null, model: string | null) => Promise<ElySkinsCatalogResponse>,
		get_memory_settings: () => Promise<MemorySettings>,
		get_skin_data_url: (skinUrl: string) => Promise<string>,
		get_system_memory: () => Promise<SystemMemoryInfo>,
		greet: (name: string) => Promise<string>,
		has_ely_web_credentials: (accountId: string) => Promise<boolean>,
		on_memory_changed: { on: (listener: (settings: MemorySettings) => void) => Promise<UnlistenFn> },
		remove_account: (accountId: string) => Promise<null>,
		reorder_accounts: (accountIds: string[]) => Promise<null>,
		save_skin_to_downloads: (username: string, skinUrl: string) => Promise<string>,
		set_active_account: (accountId: string) => Promise<null>,
		set_memory_settings: (minRamMb: number, maxRamMb: number) => Promise<MemorySettings>,
		upload_ely_skin: (accountId: string, imageBase64: string, password: string | null) => Promise<null>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }

