/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModpacksRouteImport } from './routes/modpacks'
import { Route as ScreenshotsRouteImport } from './routes/screenshots'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkinsRouteImport } from './routes/skins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpacksRoute = ModpacksRouteImport.update({
  id: '/modpacks',
  path: '/modpacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotsRoute = ScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modpacks': typeof ModpacksRoute
  '/screenshots': typeof ScreenshotsRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modpacks': typeof ModpacksRoute
  '/screenshots': typeof ScreenshotsRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modpacks': typeof ModpacksRoute
  '/screenshots': typeof ScreenshotsRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/modpacks' | '/screenshots' | '/servers' | '/settings' | '/skins'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modpacks' | '/screenshots' | '/servers' | '/settings' | '/skins'
  id:
    | '__root__'
    | '/'
    | '/modpacks'
    | '/screenshots'
    | '/servers'
    | '/settings'
    | '/skins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModpacksRoute: typeof ModpacksRoute
  ScreenshotsRoute: typeof ScreenshotsRoute
  ServersRoute: typeof ServersRoute
  SettingsRoute: typeof SettingsRoute
  SkinsRoute: typeof SkinsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpacks': {
      id: '/modpacks'
      path: '/modpacks'
      fullPath: '/modpacks'
      preLoaderRoute: typeof ModpacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshots': {
      id: '/screenshots'
      path: '/screenshots'
      fullPath: '/screenshots'
      preLoaderRoute: typeof ScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModpacksRoute: ModpacksRoute,
  ScreenshotsRoute: ScreenshotsRoute,
  ServersRoute: ServersRoute,
  SettingsRoute: SettingsRoute,
  SkinsRoute: SkinsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
